@echo off
rem Generated by setup.ps1 - launches the Marco overlay stack.
setlocal
cd /d "%~dp0"
set "MARCO_BIN=%CD%\marco.exe"
for /f "usebackq delims=" %%w in (`marco.exe wake`) do set "MARCO_VOICE_WAKE=%%w"
plugins\voice\voice.exe --model plugins\voice\model | marco.exe serve ^
  --host "OS=bridge:%CD%\marco-macros.exe" ^
  --host "Overlay=bridge:%CD%\plugins\overlay\overlay.exe" ^
  plugins\overlay\overlay.marco %*
