@echo off
rem Generated by setup.ps1 - launches the Marco overlay stack.
setlocal
cd /d "%~dp0"
set "MARCO_BIN=%CD%\marco.exe"
marco.exe serve ^
  --host "OS=bridge:%CD%\marco-macros.exe" ^
  --host "Overlay=bridge:%CD%\plugins\overlay\overlay.exe" ^
  programs\overlay.marco %*
