@echo off
rem Generated by setup.ps1 - launches the Marco overlay stack.
setlocal
cd /d "%~dp0"
set "MARCO_BIN=%CD%\marco.exe"
set "MARCO_CV=max"
set "MARCO_OCR=%CD%\plugins\ocr\ocr.exe"
set "MARCO_TESSERACT=C:\Program Files\Tesseract-OCR\tesseract.exe"
set "MARCO_VISION=%CD%\plugins\vision\vision.exe"
set "MARCO_VISION_MODEL=D:\Macros\marco\plugins\vision\models\icon_detect.onnx"
set "MARCO_ONNXRUNTIME=D:\Macros\marco\_dl\onnxruntime-win-x64-1.26.0\lib\onnxruntime.dll"
marco.exe serve ^
  --host "OS=bridge:%CD%\marco-macros.exe" ^
  --host "Vision=bridge:%CD%\plugins\vision\vision.exe" ^
  --host "Overlay=bridge:%CD%\plugins\overlay\overlay.exe" ^
  plugins\overlay\overlay.marco %*
