// Package codegen turns a macro step list into a runnable Marco route on the OS
// act. The output is the same shape as the hand-written routes under routes/
// (an actor with a Run capability that does OS clicks/sleeps/keys/types, with
// loops emitted as `repeat N times...`). It is OS-agnostic.
package codegen

import (
	"fmt"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/chaynes-simpleclouds/marco/internal/macroir"
)

// DefaultTolerance is the per-channel color slack used when a click is matched
// by image and the step didn't specify its own. Paired with screen.MatchThreshold
// (a fraction of pixels, not all), this tolerates anti-aliasing and overlays.
const DefaultTolerance = 24

// DefaultFindTimeoutMs is how long an anchored click's GATE waits to confirm before
// it clicks the recorded coordinate anyway. Short on purpose: with every click auto-
// anchored, the gate is a quick confirmation, not a load-wait — and it must never hang
// the route when a signal can't match (a toggled button, a tooltip in the crop). The
// click is correct regardless (it's the recorded/window-relative point), so failing
// fast and clicking beats waiting. Use an explicit "wait for this screen" step for a
// genuine load (that's DefaultWaitTimeoutMs).
const DefaultFindTimeoutMs = 1500

// DefaultWaitTimeoutMs is how long a "wait for this screen" step polls for the
// captured screen before giving up — longer than a click find, since it's
// explicitly there to sit through a load.
const DefaultWaitTimeoutMs = 60000

// TextSearchMargin (px) is the half-size of the box a DEMONSTRATED text anchor searches
// around its recorded click — generous enough that a label which reflowed within its
// panel is still inside it, tight enough to stay fast and avoid a stray match elsewhere.
const TextSearchMargin = 400

// DefaultTextTimeoutMs is how long a text (OCR) locator polls. It's short: a text
// anchor is for a target that MOVED but is already on screen (a reflowing UI), and
// each poll re-captures + re-OCRs (expensive), so we don't sit on it for long. When
// a text anchor backs an image gate, the gate already absorbed the loading wait.
const DefaultTextTimeoutMs = 3000

// Route renders a named macro as Marco source. name is the human command name
// (e.g. "open chest"); it becomes the route's actor (PascalCase) and the log
// label. app, when non-empty, is the application the route was taught in — the
// route brings it to the foreground first, so the route is context-aware (e.g.
// "login to facebook" focuses Chrome before clicking). The generated route runs
// on the OS act (`use os.`).
//
// A click that carries a captured Template becomes a robust image-find ("locate
// this image and click it; fall back to the recorded coordinate if not found").
// Each such template is returned in assets, keyed by the absolute path codegen
// embedded in the route (under assetDir) — the caller writes those files beside
// the route. assets is nil when no click was image-matched.
func Route(name, app string, steps []macroir.Step, assetDir string, declaredArgs ...string) (src string, assets map[string][]byte, err error) {
	actor := pascal(name)
	if actor == "" {
		return "", nil, fmt.Errorf("route name %q has no usable identifier characters", name)
	}

	declared := map[string]bool{}
	for _, a := range declaredArgs {
		declared[strings.ToLower(a)] = true
	}
	g := &gen{pts: &points{}, assetDir: assetDir, base: fileBase(name), assets: map[string][]byte{}, declared: declared}
	body, err := emit(steps, g, 1)
	if err != nil {
		return "", nil, err
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// Auto-generated by `marco teach %q`. Edit freely.\n", name)
	if app != "" {
		fmt.Fprintf(&b, "// Context: %s (brought to the foreground before running).\n", app)
	}
	b.WriteString("use os.\n")
	// A text anchor resolves through the OCR resolver plugin (the Text act).
	if g.textN > 0 {
		b.WriteString("use text.\n")
	}
	// A vision anchor resolves through the semantic detector plugin (the Vision act).
	if g.visionN > 0 {
		b.WriteString("use vision.\n")
	}
	b.WriteString("\n")
	// An anchored click needs an Anchor set type — one shape carries every resolver:
	// OS's Find reads Image/Color/X/Y, Text's Find reads Text; each ignores the rest.
	if g.anchorN > 0 {
		b.WriteString("// An on-screen target the engine resolves by SCORING signals into a confidence:\n")
		b.WriteString("// the Image crop match, the pixel Colour at the click, and how near a candidate\n")
		b.WriteString("// is to the recorded point (X,Y / window-relative RelX,RelY). Clears the bar →\n")
		b.WriteString("// click the located point (follows a moved target); below it → fall back. Text is\n")
		b.WriteString("// the OCR locator, tried when the scored signals are unsure.\n")
		b.WriteString("the Anchor is a set.\n")
		b.WriteString("this's Image is a text.\n")
		b.WriteString("this's Color is a text.    // signal: the pixel colour at X,Y\n")
		b.WriteString("this's Window is a text.   // context: the window title to act within\n")
		b.WriteString("this's Text is a text.     // locator: on-screen text to find by OCR\n")
		b.WriteString("this's Label is a text.    // locator: the control CLASS for the Vision detector\n")
		b.WriteString("this's X is a number.\n")
		b.WriteString("this's Y is a number.\n")
		b.WriteString("this's RelX is a number.   // window-relative click (resolved after Activate)\n")
		b.WriteString("this's RelY is a number.\n")
		b.WriteString("this's X1 is a number.     // search region for the Text / Vision locators\n")
		b.WriteString("this's Y1 is a number.\n")
		b.WriteString("this's X2 is a number.\n")
		b.WriteString("this's Y2 is a number.\n")
		b.WriteString("this's Tolerance is a number.\n")
		b.WriteString("this's Timeout is a number.  // ms to wait for it to appear\n\n")
	}
	fmt.Fprintf(&b, "the %s is an actor.\n\n", actor)
	b.WriteString("this can Run.\n")
	b.WriteString("this's Run does...\n")

	// Point locals are declared at the top of the action body, then the steps.
	for _, decl := range g.pts.decls {
		fmt.Fprintf(&b, "%s%s\n", indent(1), decl)
	}
	// Context-aware: focus the app the route was taught in (no-op if already in
	// front). A failure floats to the route's contract and is handled at the
	// call site. Skipped when the steps already lead with their own Activate
	// (the recorder detected the app switches), to avoid focusing twice.
	if app != "" && !(len(steps) > 0 && steps[0].Kind == macroir.StepActivate) {
		fmt.Fprintf(&b, "%sdo OS's Activate with \"%s\".\n", indent(1), escape(app))
	}
	b.WriteString(body)
	fmt.Fprintf(&b, "%sthis is ok!\n\n", indent(1))

	fmt.Fprintf(&b, "the App is a script.\n\n")
	fmt.Fprintf(&b, "do %s's Run...\n", actor)
	fmt.Fprintf(&b, "%swhen ok?\n", indent(1))
	fmt.Fprintf(&b, "%slog \"%s: done\".\n", indent(2), escape(name))
	fmt.Fprintf(&b, "%sor?\n", indent(1))
	fmt.Fprintf(&b, "%slog that's error.\n", indent(2))
	if len(g.assets) == 0 {
		g.assets = nil
	}
	return b.String(), g.assets, nil
}

// gen carries the mutable state threaded through emit: point locals, the asset
// directory + name base for template files, the accumulated assets, and the
// running anchor counter.
type gen struct {
	pts      *points
	assetDir string
	base     string
	assets   map[string][]byte
	anchorN  int
	textN    int             // anchors carrying a Text locator → emit `use text.`
	visionN  int             // anchors carrying a Vision locator → emit `use vision.`
	declared map[string]bool // declared arg names: {{name}} kept (filled at run), not a secret
}

// points allocates and declares numbered Point locals (p1, p2, …).
type points struct {
	n     int
	decls []string
}

func (p *points) add(x, y int) string {
	p.n++
	name := fmt.Sprintf("p%d", p.n)
	p.decls = append(p.decls, fmt.Sprintf("the %s is a Point with X %d, Y %d.", name, x, y))
	return name
}

// addRel declares a window-relative Point: X,Y are the absolute fallback and
// RelX,RelY the offset inside the active window. The OS host resolves RelX,RelY
// against the foreground (just-activated) window so the click lands at the same
// spot in the window on any monitor or position, falling back to X,Y if it's gone.
func (p *points) addRel(x, y, rx, ry int) string {
	p.n++
	name := fmt.Sprintf("p%d", p.n)
	p.decls = append(p.decls, fmt.Sprintf("the %s is a Point with X %d, Y %d, RelX %d, RelY %d.", name, x, y, rx, ry))
	return name
}

// clickPoint declares the Point for a click step — window-relative when the
// recorder captured an offset, else a plain absolute point.
func (p *points) clickPoint(s macroir.Step) string {
	if s.WinRel {
		return p.addRel(s.X, s.Y, s.RelX, s.RelY)
	}
	return p.add(s.X, s.Y)
}

// emit renders steps at the given indent depth.
func emit(steps []macroir.Step, g *gen, depth int) (string, error) {
	var b strings.Builder
	pad := indent(depth)
	for _, s := range steps {
		switch s.Kind {
		case macroir.StepActivate:
			fmt.Fprintf(&b, "%sdo OS's Activate with \"%s\".\n", pad, escape(s.Text))
		case macroir.StepClick:
			switch {
			case len(s.Template) > 0 || s.AnchorText != "":
				g.emitAnchoredClick(&b, s, depth) // image/colour gate and/or text locator
			case s.Button != "" && s.Button != "left":
				fmt.Fprintf(&b, "%sdo OS's Click with %q.\n", pad, s.Button)
			default:
				name := g.pts.clickPoint(s)
				fmt.Fprintf(&b, "%sdo OS's Click with %s.\n", pad, name)
			}
		case macroir.StepMove:
			name := g.pts.add(s.X, s.Y)
			fmt.Fprintf(&b, "%sdo OS's Move with %s.\n", pad, name)
		case macroir.StepWait:
			fmt.Fprintf(&b, "%sdo OS's Sleep with %d.\n", pad, s.Ms)
		case macroir.StepKey:
			count := s.Count
			if count <= 1 {
				fmt.Fprintf(&b, "%sdo OS's Key with %q.\n", pad, s.Key)
			} else {
				fmt.Fprintf(&b, "%srepeat %d times...\n", pad, count)
				fmt.Fprintf(&b, "%sdo OS's Key with %q.\n", indent(depth+1), s.Key)
			}
		case macroir.StepKeyDown:
			fmt.Fprintf(&b, "%sdo OS's KeyDown with %q.\n", pad, s.Key)
		case macroir.StepKeyUp:
			fmt.Fprintf(&b, "%sdo OS's KeyUp with %q.\n", pad, s.Key)
		case macroir.StepType:
			// {{name}} placeholders: a DECLARED arg (or numeric {{N}}) stays in the
			// text to be filled at run time; any other {{name}} becomes a Secret lookup
			// so passwords are never written into the route.
			for _, seg := range splitSecrets(s.Text, g.declared) {
				if seg.secret {
					// A declared secret arg (password/pin/…) is route-qualified so each
					// route remembers its own — "<route>:password" — while a plain typed
					// {{name}} secret keeps its global name.
					sname := seg.text
					if seg.qualified {
						sname = g.base + ":" + seg.text
					}
					fmt.Fprintf(&b, "%sdo OS's Secret with \"%s\".\n", pad, escape(sname))
				} else if seg.text != "" {
					fmt.Fprintf(&b, "%sdo OS's Type with \"%s\".\n", pad, escape(seg.text))
				}
			}
		case macroir.StepDrag:
			// No button-hold primitive yet — degrade to move-to-start + click-end.
			start := g.pts.add(s.X, s.Y)
			end := g.pts.add(s.X2, s.Y2)
			fmt.Fprintf(&b, "%s// TODO drag (no hold primitive): move to start, click end.\n", pad)
			fmt.Fprintf(&b, "%sdo OS's Move with %s.\n", pad, start)
			fmt.Fprintf(&b, "%sdo OS's Click with %s.\n", pad, end)
		case macroir.StepLoop:
			fmt.Fprintf(&b, "%srepeat %d times...\n", pad, s.Count)
			inner, err := emit(s.Steps, g, depth+1)
			if err != nil {
				return "", err
			}
			b.WriteString(inner)
		case macroir.StepFind:
			g.emitWaitImage(&b, s, depth)
		default:
			return "", fmt.Errorf("codegen: unknown step kind %q", s.Kind)
		}
	}
	return b.String(), nil
}

// emitAnchoredClick renders a click resolved by one or more anchors. There are two
// kinds, and they compose:
//
//   - GATE (Image and/or Colour): a wait gate. Find blocks until the captured
//     screen/menu appears (its pixels don't move on a static page), then we click the
//     recorded COORDINATE — exactly where you clicked, regardless of how the template
//     was cropped (capture the whole menu for context without dragging the click to
//     its centre). If it never appears we click the coordinate anyway (best effort).
//
//   - LOCATOR (Text, then Vision): used when the gate fails (or alone), because the
//     target MOVED — a reflowing UI. Text's Find returns where the WORD is now; Vision's
//     Locate returns where the nearest control of the same CLASS ("button"/"icon") is now
//     — the resolver for a control with no text and no clean edge. Each clicks THERE
//     (`that`). The locators run in order of precision — exact text, then class — and the
//     chain falls through to the recorded coordinate if none resolves (or no host wired).
//
// Anchors are declared up front (siblings, so locals stay top-level, not nested in an
// arm). A left click clicks the Point directly; a right/middle click moves there first.
func (g *gen) emitAnchoredClick(b *strings.Builder, s macroir.Step, depth int) {
	g.anchorN++
	n := g.anchorN
	pad := indent(depth)
	point := g.pts.clickPoint(s) // the recorded click coordinate (window-relative)
	hasGate := len(s.Template) > 0
	hasText := s.AnchorText != ""
	hasVision := s.AnchorVision != ""

	// clickRecorded clicks the recorded Point (the gate model / final fallback).
	clickRecorded := func(d int) {
		if s.Button == "" || s.Button == "left" {
			fmt.Fprintf(b, "%sdo OS's Click with %s.\n", indent(d), point)
			return
		}
		fmt.Fprintf(b, "%sdo OS's Move with %s.\n", indent(d), point)
		fmt.Fprintf(b, "%sdo OS's Click with %q.\n", indent(d), s.Button)
	}
	// clickFound clicks where the located text is (`that`, the Point Text's Find returns).
	clickFound := func(d int) {
		if s.Button == "" || s.Button == "left" {
			fmt.Fprintf(b, "%sdo OS's Click with that.\n", indent(d))
			return
		}
		fmt.Fprintf(b, "%sdo OS's Move with that.\n", indent(d))
		fmt.Fprintf(b, "%sdo OS's Click with %q.\n", indent(d), s.Button)
	}

	// Declare the gate anchor (Image + optional Colour) up front.
	if hasGate {
		fname := fmt.Sprintf("%s-anchor-%d.png", g.base, n)
		abs := filepath.Join(g.assetDir, fname)
		g.assets[abs] = s.Template
		tol := s.Tolerance
		if tol <= 0 {
			tol = DefaultTolerance
		}
		// The scorer needs the recorded click point on the anchor: X,Y (absolute) plus
		// RelX,RelY (window-relative) so colour/position probe the RIGHT pixel after an
		// Activate. Colour, when captured, is an extra signal at that point.
		extra := fmt.Sprintf(", X %d, Y %d", s.X, s.Y)
		if s.WinRel {
			extra += fmt.Sprintf(", RelX %d, RelY %d", s.RelX, s.RelY)
		}
		if s.Color != "" {
			extra = fmt.Sprintf(", Color \"%s\"", escape(s.Color)) + extra
		}
		if s.Window != "" {
			extra = fmt.Sprintf(", Window \"%s\"", escape(s.Window)) + extra
		}
		fmt.Fprintf(b, "%sthe a%d is an Anchor with Image \"%s\"%s, Tolerance %d, Timeout %d.\n", pad, n, escape(abs), extra, tol, DefaultFindTimeoutMs)
	}
	// A DEMONSTRATED anchor (hasGate → it carries the recorded click coordinate) restricts
	// the locator search to a box around that point: the control moved within its panel,
	// not across the screen, so a region is faster than a whole-screen scan and avoids a
	// stray match elsewhere on a busy desktop. A coordinate-less narrated anchor searches
	// the whole screen.
	region := ""
	if hasGate {
		x1, y1 := s.X-TextSearchMargin, s.Y-TextSearchMargin
		if x1 < 0 {
			x1 = 0
		}
		if y1 < 0 {
			y1 = 0
		}
		region = fmt.Sprintf(", X1 %d, Y1 %d, X2 %d, Y2 %d", x1, y1, s.X+TextSearchMargin, s.Y+TextSearchMargin)
	}

	// Declare the text locator (Text's Find: exact on-screen text).
	if hasText {
		g.textN++
		fmt.Fprintf(b, "%sthe t%d is an Anchor with Text \"%s\"%s, Timeout %d.\n", pad, n, escape(s.AnchorText), region, DefaultTextTimeoutMs)
	}
	// Declare the vision locator (Vision's Locate: the control CLASS, nearest the recorded
	// point) — the resolver for a control with no text and no clean edge.
	if hasVision {
		g.visionN++
		hint := ""
		if hasGate {
			hint = fmt.Sprintf(", X %d, Y %d", s.X, s.Y)
		}
		fmt.Fprintf(b, "%sthe v%d is an Anchor with Label \"%s\"%s%s, Timeout %d.\n", pad, n, escape(s.AnchorVision), hint, region, DefaultTextTimeoutMs)
	}

	// The locators, in order of preference: exact TEXT, then semantic CLASS, then (in
	// emitChain's base case) the recorded coordinate. Each resolves to a point and clicks
	// it; on failure it falls through to the next.
	var calls []string
	if hasText {
		calls = append(calls, fmt.Sprintf("Text's Find with t%d", n))
	}
	if hasVision {
		calls = append(calls, fmt.Sprintf("Vision's Locate with v%d", n))
	}
	var emitChain func(i, d int)
	emitChain = func(i, d int) {
		if i >= len(calls) {
			clickRecorded(d) // exhausted the locators — best-effort recorded coordinate
			return
		}
		fmt.Fprintf(b, "%sdo %s...\n", indent(d), calls[i])
		fmt.Fprintf(b, "%swhen ok?\n", indent(d+1))
		clickFound(d + 2)
		fmt.Fprintf(b, "%sor?\n", indent(d+1))
		emitChain(i+1, d+2)
	}

	if hasGate {
		fmt.Fprintf(b, "%sdo OS's Find with a%d...\n", pad, n) // scored resolve
		fmt.Fprintf(b, "%swhen ok?\n", indent(depth+1))
		clickFound(depth + 2) // confident → click the scored location (follows a moved target)
		fmt.Fprintf(b, "%sor?\n", indent(depth+1))
		emitChain(0, depth+2) // unsure — try text, then vision, then the recorded coordinate
		return
	}
	// No gate (a narrated text/vision-only anchor): run the locator chain directly.
	emitChain(0, depth)
}

// emitWaitImage renders a "wait for this screen" step: poll for the captured image
// for up to DefaultWaitTimeoutMs, then continue. It does not click — it's purely a
// barrier that sits through a load. A timeout logs a note but lets the route go on,
// so a slightly-different screen doesn't hard-fail the whole macro.
func (g *gen) emitWaitImage(b *strings.Builder, s macroir.Step, depth int) {
	g.anchorN++
	fname := fmt.Sprintf("%s-wait-%d.png", g.base, g.anchorN)
	abs := filepath.Join(g.assetDir, fname)
	g.assets[abs] = s.Template
	tol := s.Tolerance
	if tol <= 0 {
		tol = DefaultTolerance
	}
	anchor := fmt.Sprintf("w%d", g.anchorN)
	pad := indent(depth)
	fmt.Fprintf(b, "%sthe %s is an Anchor with Image \"%s\", Tolerance %d, Timeout %d.\n", pad, anchor, escape(abs), tol, DefaultWaitTimeoutMs)
	fmt.Fprintf(b, "%sdo OS's Find with %s...\n", pad, anchor)
	fmt.Fprintf(b, "%swhen ok?\n", indent(depth+1))
	fmt.Fprintf(b, "%slog \"screen ready\".\n", indent(depth+2))
	fmt.Fprintf(b, "%sor?\n", indent(depth+1))
	fmt.Fprintf(b, "%slog \"timed out waiting for screen\".\n", indent(depth+2))
}

// fileBase turns a route name into a filesystem-safe base for template files
// (lowercase, runs of non-alphanumerics collapsed to one '-').
func fileBase(name string) string {
	var b strings.Builder
	dash := false
	for _, r := range strings.ToLower(name) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			if dash && b.Len() > 0 {
				b.WriteByte('-')
			}
			dash = false
			b.WriteRune(r)
		default:
			dash = true
		}
	}
	if b.Len() == 0 {
		return "anchor"
	}
	return b.String()
}

func indent(depth int) string { return strings.Repeat("    ", depth) }

// placeholderRe matches a {{name}} placeholder. A NUMERIC name ({{1}}, {{2}}) is a
// positional run-time argument and is left in the typed text verbatim (the engine
// fills it when the route is run with `… with a, b`); a named one ({{password}}) is
// a secret looked up from the credential store.
var placeholderRe = regexp.MustCompile(`\{\{([A-Za-z0-9_-]+)\}\}`)

type segment struct {
	text      string
	secret    bool
	qualified bool // a declared secret arg → route-qualified secret name
}

// splitSecrets breaks a typed string into literal and secret segments. A numeric
// {{N}} or a declared PLAIN {{name}} stays in the literal (the run fills it); a
// declared SECRET-typed arg ({{password}}) becomes a route-qualified secret; any
// other {{name}} is a global secret.
func splitSecrets(s string, declared map[string]bool) []segment {
	var out []segment
	last := 0
	for _, m := range placeholderRe.FindAllStringSubmatchIndex(s, -1) {
		name := s[m[2]:m[3]]
		isDeclared := declared[strings.ToLower(name)]
		if isNumeric(name) || (isDeclared && !isSecretArg(name)) {
			continue // a plain arg placeholder — keep {{…}} for run-time fill
		}
		if m[0] > last {
			out = append(out, segment{text: s[last:m[0]]})
		}
		out = append(out, segment{text: name, secret: true, qualified: isDeclared})
		last = m[1]
	}
	if last < len(s) {
		out = append(out, segment{text: s[last:]})
	}
	if len(out) == 0 {
		out = append(out, segment{text: s})
	}
	return out
}

// isSecretArg reports whether a declared arg name should be handled as a secret
// (resolved from the credential store, never written into the route, masked).
func isSecretArg(name string) bool {
	switch strings.ToLower(name) {
	case "password", "pass", "passwd", "pwd", "pin", "secret", "token", "otp", "apikey", "api-key", "key":
		return true
	}
	return false
}

func isNumeric(s string) bool {
	for _, r := range s {
		if r < '0' || r > '9' {
			return false
		}
	}
	return s != ""
}

// escape escapes a string for a Marco double-quoted literal.
func escape(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "\"", "\\\"")
	s = strings.ReplaceAll(s, "\n", "\\n")
	return s
}

// pascal turns a command name into a PascalCase identifier (letters/digits only,
// first char forced to a letter).
func pascal(name string) string {
	var b strings.Builder
	upNext := true
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z':
			if upNext {
				b.WriteRune(upper(r))
			} else {
				b.WriteRune(r)
			}
			upNext = false
		case r >= '0' && r <= '9':
			if b.Len() > 0 {
				b.WriteRune(r)
			}
			upNext = false
		default:
			upNext = true
		}
	}
	return b.String()
}

func upper(r rune) rune {
	if r >= 'a' && r <= 'z' {
		return r - 32
	}
	return r
}
