// Package codegen turns a macro step list into a runnable Marco route on the OS
// act. The output is the same shape as the hand-written routes in programs/
// (an actor with a Run capability that does OS clicks/sleeps/keys/types, with
// loops emitted as `repeat N times...`). It is OS-agnostic.
package codegen

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/chaynes-simpleclouds/marco/internal/macroir"
)

// Route renders a named macro as Marco source. name is the human command name
// (e.g. "open chest"); it becomes the route's actor (PascalCase) and the log
// label. app, when non-empty, is the application the route was taught in — the
// route brings it to the foreground first, so the route is context-aware (e.g.
// "login to facebook" focuses Chrome before clicking). The generated route runs
// on the OS act (`use os.`).
func Route(name, app string, steps []macroir.Step) (string, error) {
	actor := pascal(name)
	if actor == "" {
		return "", fmt.Errorf("route name %q has no usable identifier characters", name)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// Auto-generated by `marco teach %q`. Edit freely.\n", name)
	if app != "" {
		fmt.Fprintf(&b, "// Context: %s (brought to the foreground before running).\n", app)
	}
	b.WriteString("use os.\n\n")
	fmt.Fprintf(&b, "the %s is an actor.\n\n", actor)
	b.WriteString("this can Run.\n")
	b.WriteString("this's Run does...\n")

	pts := &points{}
	body, err := emit(steps, pts, 1)
	if err != nil {
		return "", err
	}
	// Point locals are declared at the top of the action body, then the steps.
	for _, decl := range pts.decls {
		fmt.Fprintf(&b, "%s%s\n", indent(1), decl)
	}
	// Context-aware: focus the app the route was taught in (no-op if already in
	// front). A failure floats to the route's contract and is handled at the
	// call site.
	if app != "" {
		fmt.Fprintf(&b, "%sdo OS's Activate with \"%s\".\n", indent(1), escape(app))
	}
	b.WriteString(body)
	fmt.Fprintf(&b, "%sthis is ok!\n\n", indent(1))

	fmt.Fprintf(&b, "the App is a script.\n\n")
	fmt.Fprintf(&b, "do %s's Run...\n", actor)
	fmt.Fprintf(&b, "%swhen ok?\n", indent(1))
	fmt.Fprintf(&b, "%slog \"%s: done\".\n", indent(2), escape(name))
	fmt.Fprintf(&b, "%sor?\n", indent(1))
	fmt.Fprintf(&b, "%slog that's error.\n", indent(2))
	return b.String(), nil
}

// points allocates and declares numbered Point locals (p1, p2, …).
type points struct {
	n     int
	decls []string
}

func (p *points) add(x, y int) string {
	p.n++
	name := fmt.Sprintf("p%d", p.n)
	p.decls = append(p.decls, fmt.Sprintf("the %s is a Point with X %d, Y %d.", name, x, y))
	return name
}

// emit renders steps at the given indent depth.
func emit(steps []macroir.Step, pts *points, depth int) (string, error) {
	var b strings.Builder
	pad := indent(depth)
	for _, s := range steps {
		switch s.Kind {
		case macroir.StepClick:
			if s.Button != "" && s.Button != "left" {
				fmt.Fprintf(&b, "%sdo OS's Click with %q.\n", pad, s.Button)
			} else {
				name := pts.add(s.X, s.Y)
				fmt.Fprintf(&b, "%sdo OS's Click with %s.\n", pad, name)
			}
		case macroir.StepMove:
			name := pts.add(s.X, s.Y)
			fmt.Fprintf(&b, "%sdo OS's Move with %s.\n", pad, name)
		case macroir.StepWait:
			fmt.Fprintf(&b, "%sdo OS's Sleep with %d.\n", pad, s.Ms)
		case macroir.StepKey:
			count := s.Count
			if count <= 1 {
				fmt.Fprintf(&b, "%sdo OS's Key with %q.\n", pad, s.Key)
			} else {
				fmt.Fprintf(&b, "%srepeat %d times...\n", pad, count)
				fmt.Fprintf(&b, "%sdo OS's Key with %q.\n", indent(depth+1), s.Key)
			}
		case macroir.StepType:
			// {{name}} placeholders become Secret lookups so passwords are never
			// written into the route — the value lives in the OS credential store.
			for _, seg := range splitSecrets(s.Text) {
				if seg.secret {
					fmt.Fprintf(&b, "%sdo OS's Secret with \"%s\".\n", pad, escape(seg.text))
				} else if seg.text != "" {
					fmt.Fprintf(&b, "%sdo OS's Type with \"%s\".\n", pad, escape(seg.text))
				}
			}
		case macroir.StepDrag:
			// No button-hold primitive yet — degrade to move-to-start + click-end.
			start := pts.add(s.X, s.Y)
			end := pts.add(s.X2, s.Y2)
			fmt.Fprintf(&b, "%s// TODO drag (no hold primitive): move to start, click end.\n", pad)
			fmt.Fprintf(&b, "%sdo OS's Move with %s.\n", pad, start)
			fmt.Fprintf(&b, "%sdo OS's Click with %s.\n", pad, end)
		case macroir.StepLoop:
			fmt.Fprintf(&b, "%srepeat %d times...\n", pad, s.Count)
			inner, err := emit(s.Steps, pts, depth+1)
			if err != nil {
				return "", err
			}
			b.WriteString(inner)
		case macroir.StepFind:
			return "", fmt.Errorf("codegen: StepFind not implemented yet")
		default:
			return "", fmt.Errorf("codegen: unknown step kind %q", s.Kind)
		}
	}
	return b.String(), nil
}

func indent(depth int) string { return strings.Repeat("    ", depth) }

// secretRe matches a {{name}} placeholder.
var secretRe = regexp.MustCompile(`\{\{([A-Za-z0-9_-]+)\}\}`)

type segment struct {
	text   string
	secret bool
}

// splitSecrets breaks a typed string into literal and {{secret}} segments.
func splitSecrets(s string) []segment {
	var out []segment
	last := 0
	for _, m := range secretRe.FindAllStringSubmatchIndex(s, -1) {
		if m[0] > last {
			out = append(out, segment{text: s[last:m[0]]})
		}
		out = append(out, segment{text: s[m[2]:m[3]], secret: true})
		last = m[1]
	}
	if last < len(s) {
		out = append(out, segment{text: s[last:]})
	}
	if len(out) == 0 {
		out = append(out, segment{text: s})
	}
	return out
}

// escape escapes a string for a Marco double-quoted literal.
func escape(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "\"", "\\\"")
	s = strings.ReplaceAll(s, "\n", "\\n")
	return s
}

// pascal turns a command name into a PascalCase identifier (letters/digits only,
// first char forced to a letter).
func pascal(name string) string {
	var b strings.Builder
	upNext := true
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z':
			if upNext {
				b.WriteRune(upper(r))
			} else {
				b.WriteRune(r)
			}
			upNext = false
		case r >= '0' && r <= '9':
			if b.Len() > 0 {
				b.WriteRune(r)
			}
			upNext = false
		default:
			upNext = true
		}
	}
	return b.String()
}

func upper(r rune) rune {
	if r >= 'a' && r <= 'z' {
		return r - 32
	}
	return r
}
