package marcoexec

import (
	"fmt"
	"sort"
	"strings"
)

// Lower turns an operation into a complete, runnable Marco program.
//
// Source rather than a hand-built ast.File. graph.Build does take a typed *ast.File,
// but ast.Part is effectively a token stream (PartWord, PartString, PartPossessive),
// so constructing one by hand is harder to review than the Marco it stands for — and,
// deciding the matter, it would skip the parser, which makes "every generated program
// parses" untestable. The repository's own precedent is the same: codegen.Route lowers
// []macroir.Step to source and TestGeneratedRoutesCompileAndRun parses the result.
//
// The Operation is the typed representation. The source is a rendering of it.
func Lower(o Operation) (string, error) {
	if err := o.Validate(); err != nil {
		return "", err
	}
	body, err := o.body()
	if err != nil {
		return "", err
	}
	actor := actorName(string(o.Kind))

	var b strings.Builder
	// The header names no source path. It used to cite the Go files the act surfaces are
	// embedded from, which is a fact about this repository rather than about the program —
	// and a reader of a generated program has no use for it. It also put the word
	// "accessibility" into every lowered program, including ones that reach nothing of the
	// kind, which is how a test that asks "does this program touch the accessibility act"
	// gets the wrong answer.
	b.WriteString("// Generated by the Director. Every capability below is declared by the " +
		"act that names it.\n")
	for _, m := range o.Modules() {
		fmt.Fprintf(&b, "use %s.\n", m)
	}
	b.WriteString("\n")
	fmt.Fprintf(&b, "the %s is an actor.\n\n", actor)
	b.WriteString("this can Run.\n")
	b.WriteString("this's Run does...\n")
	b.WriteString(body)
	b.WriteString("    this is ok!\n\n")
	b.WriteString("the App is a script.\n\n")
	fmt.Fprintf(&b, "do %s's Run...\n", actor)
	b.WriteString("    when ok?\n")
	fmt.Fprintf(&b, "        log \"%s: done\".\n", actor)
	b.WriteString("    or?\n")
	b.WriteString("        log that's error.\n")
	return b.String(), nil
}

// body renders the capability invocations for one operation.
//
// Every literal goes through Quote. Not one uses fmt.Sprintf with a %s for user text:
// the encoder is the only thing that knows Marco's escape rules, and a single
// interpolated string here would be the hole that lets a quote or a backslash change
// what the program says.
func (o Operation) body() (string, error) {
	var b strings.Builder

	switch o.Kind {
	case KindClick:
		// OS's Click takes EITHER a Point (always left) OR a button name (always at
		// the cursor). This is the language's actual shape, not a limitation being
		// worked around: a non-left click at a point is a Move followed by Clicks.
		if o.Button != "" && o.Button != "left" {
			fmt.Fprintf(&b, "    the at is a Point with X %d, Y %d.\n", o.At.X, o.At.Y)
			b.WriteString("    do OS's Move with at.\n")
			btn, err := Quote(o.Button)
			if err != nil {
				return "", err
			}
			for i := 0; i < o.clicks(); i++ {
				fmt.Fprintf(&b, "    do OS's Click with %s.\n", btn)
			}
			break
		}
		fmt.Fprintf(&b, "    the at is a Point with X %d, Y %d.\n", o.At.X, o.At.Y)
		for i := 0; i < o.clicks(); i++ {
			b.WriteString("    do OS's Click with at.\n")
		}

	case KindMove:
		fmt.Fprintf(&b, "    the at is a Point with X %d, Y %d.\n", o.At.X, o.At.Y)
		b.WriteString("    do OS's Move with at.\n")

	case KindDrag:
		// The Drag set carries both endpoints and the button, so a drag is ONE
		// capability — press, glide and release stay atomic in the host rather than
		// being three Director calls with a window for something to move between them.
		btn := o.Button
		if btn == "" {
			btn = "left"
		}
		q, err := Quote(btn)
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "    the path is a Drag with FromX %d, FromY %d, ToX %d, ToY %d, Button %s.\n",
			o.From.X, o.From.Y, o.To.X, o.To.Y, q)
		b.WriteString("    do OS's Drag with path.\n")

	case KindKey:
		q, err := Quote(o.Chord)
		if err != nil {
			return "", err
		}
		if o.Hold > 0 {
			fmt.Fprintf(&b, "    the held is a Press with Key %s, Hold %d.\n", q, o.Hold)
			b.WriteString("    do OS's Key with held.\n")
			break
		}
		fmt.Fprintf(&b, "    do OS's Key with %s.\n", q)

	case KindNavigate:
		// One line per meaning, in the order the demonstration recorded them. No
		// collapsing of a repeated meaning into a count: the language has no repeat
		// here, and inventing one would put a loop in the program a person reads.
		for _, in := range o.Intents {
			name, err := Quote(in)
			if err != nil {
				return "", err
			}
			fmt.Fprintf(&b, "    do OS's Navigate with %s.\n", name)
		}

	case KindType:
		q, err := Quote(o.Text)
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "    do OS's Type with %s.\n", q)

	case KindTypeSecret:
		// The credential's NAME, never its value. OS's Secret exists precisely so the
		// value is fetched inside the host: it is not in this program, not in the
		// action graph, not in a diagnostic, and not in a model prompt.
		q, err := Quote(o.SecretRef)
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "    do OS's Secret with %s.\n", q)

	case KindActivate:
		q, err := Quote(o.App)
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "    do OS's Activate with %s.\n", q)

	case KindLaunch:
		q, err := Quote(o.Target)
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "    do OS's Launch with %s.\n", q)

	case KindMoveWindow:
		q, err := Quote(o.Window)
		if err != nil {
			return "", err
		}
		// Negative X and Y are ordinary: a monitor left of or above the primary one
		// has them, and %d carries the sign through unchanged.
		fmt.Fprintf(&b, "    the place is a WindowMove with Window %s, X %d, Y %d, W %d, H %d.\n",
			q, o.Bounds.X, o.Bounds.Y, o.Bounds.W, o.Bounds.H)
		b.WriteString("    do OS's MoveWindow with place.\n")

	case KindWindowState:
		qw, err := Quote(o.Window)
		if err != nil {
			return "", err
		}
		qs, err := Quote(o.State)
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "    the change is a WindowStateChange with Window %s, State %s.\n", qw, qs)
		b.WriteString("    do OS's WindowState with change.\n")

	case KindClipboardGet:
		b.WriteString("    do OS's ClipboardGet.\n")

	case KindClipboardSet:
		q, err := Quote(o.Text)
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "    do OS's ClipboardSet with %s.\n", q)

	default:
		// Every control operation renders identically — the Control set, then the one
		// capability. Handled here rather than as ten switch arms so a new structural
		// effect is a table entry in controlKinds and nothing else; a new arm that
		// forgot to bind the Control would compile and then act on nothing.
		if o.Kind.ControlKind() {
			ctl, err := o.control()
			if err != nil {
				return "", err
			}
			b.WriteString(ctl)
			caps, _ := o.Capabilities()
			fmt.Fprintf(&b, "    do %s with ctl.\n", caps[0])
			break
		}
		return "", fmt.Errorf("marcoexec: %q has no lowering", o.Kind)
	}
	return b.String(), nil
}

// control renders the Control binding, omitting fields that were not set.
//
// Omitted, not defaulted: an empty Window means "the foreground window" to the host,
// and writing Window "" would say something different and wrong.
func (o Operation) control() (string, error) {
	// WHICH NAME. A control is identified by the source's own id or by its label, never by
	// both — see Operation.Called. Validate has already refused an operation carrying
	// neither or both, so this is a choice rather than a preference.
	var fields []string
	if o.Called != "" {
		called, err := Quote(o.Called)
		if err != nil {
			return "", err
		}
		fields = append(fields, "Name "+called)
	} else {
		el, err := Quote(o.Element)
		if err != nil {
			return "", err
		}
		fields = append(fields, "Element "+el)
	}
	if o.Window != "" {
		w, err := Quote(o.Window)
		if err != nil {
			return "", err
		}
		fields = append(fields, "Window "+w)
	}
	if o.Kind == KindSetValue {
		v, err := Quote(o.Value)
		if err != nil {
			return "", err
		}
		fields = append(fields, "Value "+v)
	}
	if o.MaxNodes > 0 {
		fields = append(fields, fmt.Sprintf("MaxNodes %d", o.MaxNodes))
	}
	return fmt.Sprintf("    the ctl is a Control with %s.\n", strings.Join(fields, ", ")), nil
}

// Redact renders source with secret material removed.
//
// Only ever needed for KindTypeSecret, and even there the source carries a NAME
// rather than a value — the redaction is belt and braces, so that a credential name
// that happens to be sensitive ("prod-root-password") never reaches a log either.
func Redact(o Operation, source string) string {
	if o.Sensitive() && o.Text != "" {
		// A sensitive captured value HAD to be in the source to be executed, and must
		// not survive in the copy kept for diagnostics. Replacing the literal rather
		// than dropping the line keeps the retained source readable as a shape — which
		// capability ran, against what — while carrying none of the content.
		//
		// Done by literal substitution rather than by re-lowering a blanked operation,
		// because the retained source must correspond to what actually ran; a
		// separately generated string could differ from it and nobody would know.
		quoted, err := Quote(o.Text)
		if err == nil {
			source = strings.ReplaceAll(source, quoted, `"<redacted: program value>"`)
		}
	}
	if !o.Secret() {
		return source
	}
	var out []string
	for _, line := range strings.Split(source, "\n") {
		if strings.Contains(line, "OS's Secret with") {
			indent := line[:len(line)-len(strings.TrimLeft(line, " \t"))]
			out = append(out, indent+"do OS's Secret with <redacted>.")
			continue
		}
		out = append(out, line)
	}
	return strings.Join(out, "\n")
}

// modulesFor returns the union of modules a set of operations needs, sorted.
func modulesFor(ops []Operation) []string {
	seen := map[string]bool{}
	for _, o := range ops {
		for _, m := range o.Modules() {
			seen[m] = true
		}
	}
	out := make([]string, 0, len(seen))
	for m := range seen {
		out = append(out, m)
	}
	sort.Strings(out)
	return out
}

// actorPrefix keeps a generated actor from colliding with a declared symbol.
//
// Found by the compiler, not by reasoning: lowering a drag produced
// `the Drag is an actor.` while os.marco already declares `the Drag is a set.`, and
// the build failed with `duplicate symbol "Drag"`. Point, Press, Control, Clipboard,
// WindowMove and WindowStateChange are all live mines of the same kind. A prefix the
// act surfaces will never use removes the whole class rather than blacklisting names
// one at a time as each is discovered.
const actorPrefix = "Director"

// actorName turns a kind into a valid, collision-proof Marco actor name.
func actorName(s string) string { return actorPrefix + bareActorName(s) }

func bareActorName(s string) string {
	var b strings.Builder
	upper := true
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z':
			if upper {
				b.WriteRune(toUpper(r))
				upper = false
			} else {
				b.WriteRune(r)
			}
		case r >= '0' && r <= '9' && b.Len() > 0:
			b.WriteRune(r)
		default:
			upper = true
		}
	}
	if b.Len() == 0 {
		return "Step"
	}
	return b.String()
}

func toUpper(r rune) rune {
	if r >= 'a' && r <= 'z' {
		return r - 32
	}
	return r
}
