// Package goal is the Director's model of what a user WANTS, above the model of what
// the Director DOES.
//
// The governing rules:
//
//	The user describes the desired outcome.
//	The Director expands goals into semantic programs.
//	Marco still executes only deterministic primitive operations.
//	Decomposition is deterministic, typed, explainable and replayable.
//
// The gap this closes is the last one between "the Director executes programs well" and
// "the Director is useful": everything below this layer expects the user to describe
// HOW. "Rename this file to Budget" was not a request the Director could take — it had
// to be said as focus, then press Rename, then wait, then type, then confirm, and a user
// who knew to say that did not need a Director.
//
// So a Goal names an OUTCOME, a Procedure is the typed, hand-written expansion of that
// outcome into semantic steps, and what comes out is an ordinary program.Program. That
// last part is the load-bearing one: nothing downstream changes. Variables, collections,
// control flow, clarification, replay and verification keep working because the thing
// they receive is the same thing they have always received.
//
// What this package deliberately is NOT: procedures are not generated by a language
// model, are not recursive, and are not user-authored. Each of those makes the expansion
// something that cannot be shown to a person in full before it runs, which is the property
// the whole design rests on.
//
// A procedure MAY now be LEARNED — extracted from a demonstration the user performed and
// then approved (see internal/director/demo). That is not an exception to the rule above,
// and the difference is worth being exact about: a learned procedure is typed data
// produced by stated rules over recorded semantics, every one of which records why it
// fired, and it is shown to the user in full and installed only when they accept it. It
// reaches this package as an ordinary Procedure and nothing downstream can tell it from a
// hand-written one — except through Learned, which decides precedence and disclosure and
// nothing else.
package goal

import (
	"fmt"
	"sort"
	"strings"

	"github.com/chaynes-simpleclouds/marco/internal/director/binding"
	"github.com/chaynes-simpleclouds/marco/pkg/directorapi"
)

// Kind names an outcome a user can ask for.
//
// String-typed like the rest of the Director's vocabularies, so a goal serialises
// readably into the action graph and a procedure can be contributed without a Go enum
// change.
type Kind string

const (
	CreateFolder       Kind = "create_folder"
	Rename             Kind = "rename"
	Duplicate          Kind = "duplicate"
	Delete             Kind = "delete"
	Save               Kind = "save"
	SaveAs             Kind = "save_as"
	Print              Kind = "print"
	OpenSettings       Kind = "open_settings"
	OpenFile           Kind = "open_file"
	CloseWithoutSaving Kind = "close_without_saving"
	CreateTab          Kind = "create_tab"
	Download           Kind = "download"
	Move               Kind = "move"
	Copy               Kind = "copy"
	Paste              Kind = "paste"
	// Sort reorders a list, a folder, a mailbox, a container. A general outcome that
	// arrived with the first capability pack and is not a game concept: a file manager,
	// a mail client and a music library all have one.
	Sort Kind = "sort"
	// Craft makes a new thing of a named kind from a catalogue — a recipe, a template,
	// a build target. Also general, and also arrived with the first pack: the shape is
	// "choose what to make, then start making it", which is a build tool's New Project
	// as much as it is a workbench.
	Craft Kind = "craft"
)

// Vocabulary is every goal, in a stable order.
//
// One list, so `director goals`, the completeness tests and the registry all read from
// the same place. A goal in the vocabulary with no procedure is a hole the tests close.
var Vocabulary = []Kind{
	CreateFolder, Rename, Duplicate, Delete, Save, SaveAs, Print,
	OpenSettings, OpenFile, CloseWithoutSaving, CreateTab, Download,
	Move, Copy, Paste, Sort, Craft,
}

// Known reports whether a kind is in the vocabulary.
func (k Kind) Known() bool {
	for _, v := range Vocabulary {
		if v == k {
			return true
		}
	}
	return false
}

// Describe renders a goal for a person.
func (k Kind) Describe() string {
	if s, ok := goalPhrases[k]; ok {
		return s
	}
	return strings.ReplaceAll(string(k), "_", " ")
}

var goalPhrases = map[Kind]string{
	CreateFolder:       "create a folder",
	Rename:             "rename",
	Duplicate:          "duplicate",
	Delete:             "delete",
	Save:               "save",
	SaveAs:             "save under a new name",
	Print:              "print",
	OpenSettings:       "open settings",
	OpenFile:           "open",
	CloseWithoutSaving: "close without saving",
	CreateTab:          "create a new tab",
	Download:           "download",
	Move:               "move",
	Copy:               "copy",
	Paste:              "paste",
	Sort:               "sort",
	Craft:              "make",
}

// Parameter names. Constants rather than bare strings because a procedure reads what a
// parser wrote, and a typo in either would produce a goal that expands into a program
// missing the one piece of information it needed.
const (
	// ParamName is the new name, for Rename / CreateFolder / SaveAs.
	ParamName = "name"
	// ParamDestination is where something goes, for Move.
	ParamDestination = "destination"
)

// Context is what the goal is about, beyond the verb.
type Context struct {
	// Application is the app the request is aimed at, empty for the active one.
	Application string
	// Target is the user's phrase for the thing acted on ("this file", "Budget.txt").
	// Left as a PHRASE: resolution happens when the produced program's step runs, so a
	// goal that carried a resolved element would be carrying a handle from before
	// anything on screen had a chance to move.
	Target string
	// TargetIsImplicit marks "this" / "that" — the user pointed rather than named.
	TargetIsImplicit bool
}

// Goal is one outcome the user asked for.
type Goal struct {
	Kind Kind `json:"kind"`
	// Parameters carries the goal's own data — the new name, the destination.
	Parameters map[string]string `json:"parameters,omitempty"`
	Context    Context           `json:"context"`
	// Phrase is the user's words, kept for the trace and for a clarification that has
	// to quote them back.
	Phrase string `json:"phrase,omitempty"`
}

// Param reads a parameter, empty when unset.
func (g Goal) Param(name string) string { return g.Parameters[name] }

// Describe renders the goal for a person.
func (g Goal) Describe() string {
	out := g.Kind.Describe()
	if t := g.Context.Target; t != "" {
		out += " " + t
	}
	if n := g.Param(ParamName); n != "" {
		out += " to " + n
	}
	if d := g.Param(ParamDestination); d != "" {
		out += " to " + d
	}
	return out
}

// Requirement is a precondition a procedure needs before it can expand.
//
//	Every procedure declares required conditions. If not, return a semantic
//	refusal BEFORE execution.
//
// Checked at expansion time rather than discovered at step 3, because a rename that
// gets as far as focusing the file and then finds it has no new name has already moved
// the user's focus for nothing.
type Requirement string

const (
	// RequiresTarget: the goal needs something to act on.
	RequiresTarget Requirement = "target"
	// RequiresName: the goal needs a new name.
	RequiresName Requirement = "name"
	// RequiresDestination: the goal needs somewhere to put it.
	RequiresDestination Requirement = "destination"
)

// Describe renders a requirement as the question it implies.
func (r Requirement) Describe() string {
	switch r {
	case RequiresTarget:
		return "which one?"
	case RequiresName:
		return "what should it be called?"
	case RequiresDestination:
		return "where should it go?"
	}
	return string(r)
}

// Safety is what a procedure will do, declared before it runs.
//
//	Procedures must declare estimated mutations, destructive effects, external
//	effects and confirmation requirements. The policy engine evaluates procedures
//	before expansion.
//
// Declared rather than derived from the expanded steps, and that is deliberate: the
// steps say what will be pressed, and only the procedure's author knows what pressing
// it MEANS. "Invoke the Delete menu item" is three low-risk semantic actions and one
// irreversible outcome.
type Safety struct {
	// Mutations is how many steps change something the user would notice. An estimate
	// by definition — a rename is one mutation however many steps carry it out.
	Mutations int `json:"mutations"`
	// Destructive: it removes or overwrites something.
	Destructive bool `json:"destructive"`
	// External: it is visible outside this machine — sent, posted, printed.
	External bool `json:"external"`
	// Irreversible: no ordinary action undoes it.
	Irreversible bool `json:"irreversible"`
	// RequiresConfirmation asks for the user's word before anything runs. A procedure
	// may demand one; policy may add one; neither may remove one.
	RequiresConfirmation bool `json:"requires_confirmation"`
	// Risk is the level policy evaluates.
	Risk directorapi.RiskLevel `json:"risk"`
}

// Directive is one step of a procedure, before it becomes an Intent.
//
// A typed instruction rather than a phrase. Procedures that emitted English would have
// to be parsed back, which means the expansion could fail on its own output and a
// procedure's correctness would depend on the parser's mood.
type Directive struct {
	// Verb is what to do: a semantic action kind, "focus", or "edit".
	Semantic directorapi.SemanticActionKind
	// Focus makes this a focus step instead.
	Focus bool
	// SetText makes this an edit that sets the target's value to Text.
	SetText bool
	Text    string

	// Target is the phrase naming the control, empty for the focused context.
	//
	// A USER-supplied name — a file, a folder — rather than a UI label. A procedure
	// naming a control of its own uses Role instead, so it is not tied to English.
	Target string
	// Role names a control by what it MEANS. Resolved through the role's ordered
	// aliases plus whatever a platform adapter supplies, so "the control that discards
	// changes" finds "Nicht speichern" as readily as "Don't Save".
	Role ControlRole
	// TargetEditor marks a step acting on the INLINE EDITOR a previous step opened on
	// the bound object — the in-place rename box, not the item and not whatever holds
	// focus.
	//
	// Necessary because "whatever holds focus" is dangerous in exactly this situation: a
	// File Explorer details view already contains an Edit control per column per row,
	// and the one in the selected row's Name column holds the filename and a
	// ValuePattern. Typing into it changes a caption and renames nothing. That is what
	// the first live attempt did.
	TargetEditor bool
	// TargetDeictic marks a step whose target is "the one the user pointed at" —
	// "rename THIS file". It is not a label and must not be searched for as one, so
	// the step is aimed at whatever holds focus or selection instead.
	//
	// A flag rather than a magic Target value, because the two are genuinely different
	// kinds of thing: one is a name to resolve, the other is a way of resolving.
	TargetDeictic bool
	// Phrase is the human description of this step, for the plan and the trace.
	Phrase string
	// Preconditions must hold before the step runs. Evaluated as semantic waits by the
	// program layer — never as sleeps, which is why "wait until editable" is expressed
	// here rather than as a step of its own.
	Preconditions []directorapi.Condition
	// BestEffort marks a step whose verification may be inconclusive without failing
	// the program. Used only where the World Model genuinely cannot prove the outcome.
	BestEffort bool
}

// Procedure is the typed expansion of one goal.
type Procedure struct {
	// Name identifies it in diagnostics ("generic rename", "explorer rename").
	Name string `json:"name"`
	Goal Kind   `json:"goal"`
	// Applications this procedure serves. EMPTY MEANS GENERIC — it serves any
	// application that has no more specific procedure.
	Applications []string `json:"applications,omitempty"`
	// Requires are the preconditions checked before expansion.
	Requires []Requirement `json:"requires,omitempty"`
	// Expect is the kind of object this procedure's DEICTIC target must be.
	//
	// Declared per procedure rather than inferred from the goal, because the same goal
	// means different things in different applications: "rename" in Explorer points at
	// a file, and in VS Code at a symbol. A procedure that emits a deictic directive
	// and declares nothing here is refused at expansion — silence would become "any
	// focused thing will do", which is exactly the hazard the binding layer exists to
	// remove.
	Expect binding.ObjectKind `json:"expects,omitempty"`
	Safety Safety             `json:"safety"`
	// Learned marks a procedure extracted from a demonstration the user performed on
	// this machine and then approved.
	//
	// It is not a lesser kind of procedure — a learned one expands, validates, binds,
	// confirms, lowers and verifies by exactly the path a built-in does, and nothing
	// downstream reads this field. What it decides is PRECEDENCE, in one place
	// (SelectProcedure): between two procedures that constrain the same amount, the one
	// the user demonstrated here wins over the one written for desktops in general.
	//
	// It is also disclosed. A learned procedure says so in `director procedures`, in its
	// name, and in the plan of every request it serves, because a user about to let a
	// procedure act on their files is entitled to know where it came from.
	Learned bool `json:"learned,omitempty"`
	// Why explains the shape of the expansion, for `director explain goal`.
	Why string `json:"why,omitempty"`
	// Steps produces the directives for a goal. Deterministic: the same goal in the
	// same application produces the same steps, every time.
	Steps func(Goal) ([]Directive, error) `json:"-"`
}

// Generic reports whether this procedure serves any application.
func (p Procedure) Generic() bool { return len(p.Applications) == 0 }

// Serves reports whether this procedure applies to an application.
func (p Procedure) Serves(app string) bool {
	if p.Generic() {
		return true
	}
	for _, a := range p.Applications {
		if strings.EqualFold(a, app) {
			return true
		}
	}
	return false
}

// Registry holds the procedures.
//
// A registry rather than a switch so an application-specific procedure is an ENTRY
// rather than an edit to a growing function, and so `director procedures` can list what
// exists without a second copy of the list.
type Registry struct {
	procedures []Procedure
}

// NewRegistry returns the built-in library.
func NewRegistry() *Registry {
	r := &Registry{}
	for _, p := range library() {
		r.Register(p)
	}
	return r
}

// Register adds a procedure.
func (r *Registry) Register(p Procedure) { r.procedures = append(r.procedures, p) }

// All returns every procedure, generic first then by name, for listing.
func (r *Registry) All() []Procedure {
	out := make([]Procedure, len(r.procedures))
	copy(out, r.procedures)
	sort.SliceStable(out, func(i, j int) bool {
		if out[i].Goal != out[j].Goal {
			return out[i].Goal < out[j].Goal
		}
		if out[i].Generic() != out[j].Generic() {
			return out[i].Generic()
		}
		return out[i].Name < out[j].Name
	})
	return out
}

// Find returns a procedure by name.
func (r *Registry) Find(name string) (Procedure, bool) {
	for _, p := range r.procedures {
		if strings.EqualFold(p.Name, name) {
			return p, true
		}
	}
	return Procedure{}, false
}

// Missing returns the requirements this goal does not satisfy.
//
// The whole list rather than the first, so a request missing two things asks about both
// instead of playing twenty questions.
func (p Procedure) Missing(g Goal) []Requirement {
	var out []Requirement
	for _, req := range p.Requires {
		switch req {
		case RequiresTarget:
			if strings.TrimSpace(g.Context.Target) == "" && !g.Context.TargetIsImplicit {
				out = append(out, req)
			}
		case RequiresName:
			if strings.TrimSpace(g.Param(ParamName)) == "" {
				out = append(out, req)
			}
		case RequiresDestination:
			if strings.TrimSpace(g.Param(ParamDestination)) == "" {
				out = append(out, req)
			}
		}
	}
	return out
}

// Refusal is a goal that cannot be expanded, and why.
//
// A typed refusal rather than an error string: a missing requirement is a QUESTION the
// front-end can ask, and flattening it into prose would make the caller parse English
// to find out what to ask for.
type Refusal struct {
	Goal Kind `json:"goal"`
	// Missing are the requirements that were not satisfied.
	Missing []Requirement `json:"missing,omitempty"`
	// Reason is the sentence to show.
	Reason string `json:"reason"`
}

func (r Refusal) Error() string { return r.Reason }

// Question renders the refusal as the question to ask the user.
func (r Refusal) Question() string {
	if len(r.Missing) == 0 {
		return r.Reason
	}
	parts := make([]string, 0, len(r.Missing))
	for _, m := range r.Missing {
		parts = append(parts, m.Describe())
	}
	return fmt.Sprintf("%s — %s", r.Goal.Describe(), strings.Join(parts, " "))
}
