package main

import (
	"net/http"
	"strconv"
	"strings"
	"testing"

	"github.com/chaynes-simpleclouds/marco/internal/director/marcoexec"
	"github.com/chaynes-simpleclouds/marco/internal/driver"
	"github.com/chaynes-simpleclouds/marco/internal/routes"
)

// The step editor over a LEARNED play.
//
// The source is generated by the real lowering — `marcoexec` — rather than pasted in, so this
// cannot pass against a shape Director stopped writing. If the generator changes its indentation
// or its guards, these fail, which is the point: the editor's parsing and the Director's writing
// are one agreement between two packages.

// learnedSrc is what Director writes down after it has verified a route: an entry condition, the
// steps inside its `ok` arm, and a postcondition that is the only way to `ok!`.
func learnedSrc(t *testing.T) string {
	t.Helper()
	src, err := marcoexec.LowerActionsBetween("MouseSettings", "Open", "Home", "Mouse settings",
		[][]marcoexec.PlayAction{
			{marcoexec.Navigate("down"), marcoexec.Navigate("confirm")},
			{marcoexec.Press("Mouse", "button")},
		})
	if err != nil {
		t.Fatal(err)
	}
	// It is a play Marco accepts. Everything below is about SHOWING it, so it had better be one.
	if err := driver.CheckSource(src); err != nil {
		t.Fatalf("the generated learned play does not compile: %v\n%s", err, src)
	}
	return src
}

// A learned play renders as its steps, not as one row of raw source.
//
// It used to render as exactly one row — `Screen's Showing with "Home"`, unlabelled — because
// parseSteps recognised indent 4 and 8 and a learned play's steps are at 12. The one surface built
// for changing a play could not show the play Marco is named for learning.
func TestALearnedPlayShowsItsStepsInTheEditor(t *testing.T) {
	e := &editor{src: learnedSrc(t)}
	steps := e.parseSteps()

	if len(steps) < 3 {
		t.Fatalf("a learned play rendered as %d row(s), which is the defect:\n%+v\n%s",
			len(steps), steps, e.src)
	}
	// Every row a person reads: the two screen checks, and the three things the play does.
	var got []string
	for _, s := range steps {
		got = append(got, s.Kind+":"+s.Label)
	}
	want := []string{
		`check:Starts on "Home"`,
		"action:Navigate down",
		"action:Navigate confirm",
		`action:Press "Mouse"`,
		`check:Ends on "Mouse settings"`,
	}
	if strings.Join(got, " | ") != strings.Join(want, " | ") {
		t.Errorf("rows =\n  %s\nwant\n  %s", strings.Join(got, "\n  "), strings.Join(want, "\n  "))
	}
	// The navigation steps are EDITABLE — the demonstration going one row too far is the single
	// most likely thing anybody will want to correct.
	for _, s := range steps {
		if s.Kind != "action" || s.Act == "" {
			continue
		}
		if s.Act != "navigate" {
			t.Errorf("step %q has subtype %q, want navigate", s.Label, s.Act)
		}
		if s.Text == "" {
			t.Errorf("step %q carries no editable literal", s.Label)
		}
	}
	// A CHECK is shown and is not an editable action: it is the play's claim about the world.
	for _, s := range steps {
		if s.Kind == "check" && (s.Act != "" || s.Text != "") {
			t.Errorf("a screen check was offered as an editable action: %+v", s)
		}
	}
	// And every row points at a real line, so ✕ and + act on the source they name.
	lines := strings.Split(e.src, "\n")
	for _, s := range steps {
		if s.Line < 0 || s.Line >= len(lines) || strings.TrimSpace(lines[s.Line]) == "" {
			t.Errorf("row %q points at line %d, which is not a statement", s.Label, s.Line)
		}
	}
}

// An ordinary play is untouched by the body-indent rule: its steps are still at indent 4 and it
// has no screen checks to show.
//
// The guard for the mutation "always look 8 spaces deeper", which the learned test alone would let
// through — and the reason the rule is structural rather than a flag on the play.
func TestAnOrdinaryPlayStillShowsItsStepsAtTheTopLevel(t *testing.T) {
	e := &editor{src: editSample}
	if got := bodyIndent(editSample); got != 4 {
		t.Fatalf("bodyIndent(an ordinary play) = %d, want 4", got)
	}
	for _, s := range e.parseSteps() {
		if s.Kind == "check" {
			t.Errorf("an ordinary play grew a screen check: %+v", s)
		}
	}
}

// Editing a learned play's step saves, and what is written is still a play Marco can run.
//
// This is what makes the row worth rendering. Phase 3 made an edited learned play an ordinary play
// that runs locally against its OWN source — so a correction typed here is the correction that
// runs, and the compile gate on the way out is what keeps that promise honest.
func TestEditingALearnedPlaysStepSavesAndStillCompiles(t *testing.T) {
	e := newTestEditor(t)
	src := learnedSrc(t)
	rt := routes.Route{App: "settings", Focus: true, Slug: "open-mouse-settings"}
	if err := e.reg.Save(rt, src); err != nil {
		t.Fatal(err)
	}
	openForEdit(t, e, rt)

	// The correction a person actually makes: the demonstration went down, and it should go up.
	var line int
	for _, s := range e.parseSteps() {
		if s.Act == "navigate" && s.Text == "down" {
			line = s.Line
		}
	}
	if line == 0 {
		t.Fatalf("no editable navigate step to correct:\n%s", src)
	}
	w := postSave(t, e, saveReq{Texts: map[string]string{strconv.Itoa(line): "up"}})
	if w.Code != http.StatusOK {
		t.Fatalf("POST /api/save = %d: %s", w.Code, w.Body)
	}
	if !strings.Contains(e.src, `do OS's Navigate with "up".`) {
		t.Errorf("the correction did not reach the source:\n%s", e.src)
	}
	if strings.Contains(e.src, `do OS's Navigate with "down".`) {
		t.Errorf("the old step survived the correction:\n%s", e.src)
	}
	if err := driver.CheckSource(e.src); err != nil {
		t.Errorf("the edited learned play no longer compiles: %v", err)
	}
	// The rows still read the same way afterwards — the edit did not cost the play its shape.
	if n := len(e.parseSteps()); n != 5 {
		t.Errorf("after the edit the play renders as %d rows, want 5", n)
	}
}
